#!/usr/bin/env ruby
# frozen_string_literal: true

require 'curd'

require 'cuke_modeler'
require 'optparse'
require 'tty-spinner'

class Curdle

  def initialize
    @spinner = TTY::Spinner.new(':spinner :title', format: :dots_2, clear: true)
  end

  def update(feature_file)
    @spinner.update(title: feature_file.name)
    @spinner.auto_spin
  end

  def run
    output_dir = 'cucumber-doc'

    OptionParser.new do |opts|
      opts.banner = 'Usage: curd <feature_path>'
      opts.on('-oDIRECTORY',
              '--out DIRECTORY',
              'The output directory') do |dir|
        output_dir = dir
      end
    end.parse!

    features = ARGV.first || 'features'

    Curd.configure do |config|
      config.output_dir = output_dir
    end

    Curd.engine.add_observer(self)

    Curd.process(features)
    @spinner.stop
  end
end

Curdle.new.run